services:
  spark:
    image: bitnami/spark:4.0.0
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "8081:8081"
      - "7077:7077"
  spark-worker-1:
    image: bitnami/spark:4.0.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark
  spark-worker-2:
    image: bitnami/spark:4.0.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark
